### ISSUE TITLE
Difficulty with nhanesA and pre pandemic data

### ISSUE THREAD

**Issue by lamisipam** [cjendres1/nhanes#16]
Dear Mr. Endres,

Thank you for creating the nhanesA package, it has made working with the NHANES data easier.

Please I am having difficulty with importing data from the 2017-2020 pre pandemic data.
Wondering if others have also encountered similar problems and what the solution is.

For eg the following code works for all other years but not the 2017-2020 data

nhanesTableVars(data_group="DEMO", nh_table="P_DEMO",namesonly = TRUE)

Thank you

**Comment by cjendres1** [comment]
This fix has been included in nhanesA version 0.7.3 uploaded on 5/21/2023.
nhanesTableVars is now compatible with pre-pandemic data and should be working normally.
