### ISSUE TITLE
Add URLs of NHANES Data.File and Doc.File

### ISSUE THREAD

**Issue by rsgoncalves** [cjendres1/nhanes#23]
As additional columns in the data frame returned by the nhanesA::nhanesSearchTableNames() function (as discussed in https://github.com/ccb-hms/phonto/issues/22).

**Comment by cjendres1** [comment]
Added option includeurl to nhanesSearchTableNames, which inserts both document and data url's. 
This is available in the current git version and will be included with the next CRAN release.
