### ISSUE TITLE
load translated data by default

### ISSUE THREAD

**Issue by ainilaha** [cjendres1/nhanes#28]
Hi Chris

Could you update `nhanes(nh_table, includelabels = FALSE)` to `nhanes(nh_table, includelabels = FALSE, translated = TRUE)` by adding `translated = TRUE` parameter?  In the docker version, the function loads the translated data unless the users explicitly want to load the raw data by set `translated = FALSE`.
For example,
`nhanes("DEMO_C")` # By default, it would be better if it loads the categorical variables such as gender (`RIAGENDR`) column should fill with `Male` and `Female` , and race(RIDRETH1) column contains `Mexican American, Other Hispanic,Non-Hispanic White...`  instead of the integer numbers.

Thanks,
Laha

**Comment by cjendres1** [comment]
Laha, I believe your addition probably resolves the issue, but I'm going to leave this open to see if any problems arise.
In addition to warnings that you suppressed, I suppressed messages because I don't think we want all the translated columns to be written for routine data download.

**Comment by cjendres1** [comment]
So far so good. Will assume that the translate by default option works until proven otherwise.
