### ISSUE TITLE
"Tables" functions returning errors

### ISSUE THREAD

**Issue by dhicks** [cjendres1/nhanes#3]
I've just installed nhanesA, and encountered errors trying to follow the vignette:  <https://cran.r-project.org/web/packages/nhanesA/vignettes/Introducing_nhanesA.html>

In particular: 
```
> nhanesTables('EXAM', 2005)
Error in `[.data.frame`(df, , c("Data.File.Name", "Data.File.Description")) : 
  undefined columns selected
> nhanesTableVars('EXAM', 'BMX_D')
Error in nhanesTableVars("EXAM", "BMX_D") : 
  Table BMX_D not present in the EXAM survey
```

However, `bmx_d <- nhanes('BMX_D')` appears to be working as expected.

**Comment by cjendres1** [comment]
There has been a revision to the NHANES website and some of the HTML has changed. I expect to have this resolved within the next couple days.

**Comment by cjendres1** [comment]
Revised package (nhanesA 0.6.4.1) is now up on CRAN. Am closing this ticket, but will continue to investigate as some nhanesA functions (especially nhanesSearch) are having performance issues with the new NHANES website.
