### ISSUE TITLE
hopping analysis functions can be added

### ISSUE THREAD

**Issue by wangyh97** [cjendres1/nhanes#44]
due to the weighted design of NHANES，many statistical works require weight variable, the detailed algorithm really confuses me, hope one day there can be easy-to-use API, best appreciation :)

**Comment by cjendres1** [comment]
Hi,
We're currently working up documentation for analysis that will include how to apply survey weights. We may add another vignette for that purpose within the next month or so.
Thanks for using nhanesA!

**Comment by cjendres1** [comment]
[A new vignette has been added.](https://raw.githack.com/cjendres1/nhanes/master/vignettes/UsingSurveyWeights.html)
