### ISSUE TITLE
Import data issue

### ISSUE THREAD

**Issue by BryanBoule** [cjendres1/nhanes#5]
Hi,

When I run the command nhanesTables('DEMO', 2015), I get all the available tables in 2015. However, when I type nhanes('DEMO_I') to load the table, I get the following error message : 
_simpleWarning in download.file(url, tf, mode = "wb", quiet = TRUE): cannot open URL 'https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/DEMO_I.XPT': HTTP status was '404 Not Found'_
I think the route has changed and not being updated on this project.
What should I do to fix the problem ?

In addition, is it possible to make the 2016, 2017 and 2018 years available in the package ?

Regards,

Bryan

**Comment by cjendres1** [comment]
Hi Bryan,
That command appears to be working now. It's possible that the NHANES server was down when you tried to connect. Please try the same command and let me know if you still cannot download the file.
As long as the CDC sticks to their naming convention, you'll be able to access any 2017-2018 data as soon as they're available on the NHANES website.

**Comment by cjendres1** [comment]
Am closing this issue.  In the next release I will add comments to the documentation that the error message you reported likely indicates that the NHANES server is down.
