### ISSUE TITLE
Update minimum R version requirement?

### ISSUE THREAD

**Issue by deepayan** [cjendres1/nhanes#57]
nhanesA currently depends on `R >= 3.0.0`, but @rgentlem 's code already uses the base pipe operator `|>`, which will not actually work in `R < 4.1.0`. We could of course change them to `%>%`, but I prefer the more efficient and better error-handling native pipe.

Is it OK to increase the dependency to `R >= 4.1.0` (which is now almost 2.5 years old)?

**Comment by cjendres1** [comment]
That's fine by me. If we do that, should we replace all `$>$` with `|>` and remove the dependency on magrittr?

**Comment by rgentlem** [comment]
that would be nice -

**Comment by deepayan** [comment]
Yes, I also think that would be best. I will also replace `str_c()` with `paste0()` which seems to be around 10 times faster. There will still be other uses of stringr functions which have no obvious base analog, so those can remain unchanged.

I will submit a PR in a day or two.

**Comment by cjendres1** [comment]
This was resolved in cleanup 2 PR.
