### ISSUE TITLE
Bug when nhanesSearch should return NULL

### ISSUE THREAD

**Issue by rpouillot** [cjendres1/nhanes#6]
Bug when nhanesSearch should return NULL. e.g.

`nhanesSearch("creatinine", ystart=1999, ystop=2017, ignore.case=TRUE)`

**Comment by cjendres1** [comment]
Identified the bug and just submitted the fix to CRAN.

**Comment by cjendres1** [comment]
Updated package (nhanesA 6.5.3) is now in CRAN. Please try it out when you get a chance.

**Comment by rpouillot** [comment]
Looks good. Thanks -
