### ISSUE TITLE
Should we use factors?

### ISSUE THREAD

**Issue by deepayan** [cjendres1/nhanes#63]
The `nhanes(translated = TRUE)` function currently converts categorical variables into factors. Is this a good idea? Often we would want to combine data across cycles, and if the factor levels do not match across cycles, the result may not be what we expect. 

I haven't checked to see if this problem is widespread, but here is one example (look at `ALQ110`):

```
> str(nhanes("ALQ_H"))
'data.frame':	5924 obs. of  10 variables:
 $ SEQN   : num  73557 73558 73559 73561 73562 ...
 $ ALQ101 : Factor w/ 3 levels "Yes","No","Don't know": 1 1 1 1 1 2 1 1 1 2 ...
 $ ALQ110 : Factor w/ 3 levels "Yes","No","Don't know": NA NA NA NA NA 1 NA NA NA 1 ...
 $ ALQ120Q: num  1 7 0 0 5 2 1 4 2 2 ...
 $ ALQ120U: Factor w/ 3 levels "Week","Month",..: 3 1 NA NA 3 3 1 1 1 3 ...
 $ ALQ130 : num  1 4 NA NA 1 1 1 3 2 1 ...
 $ ALQ141Q: num  0 2 NA NA 0 0 0 0 1 0 ...
 $ ALQ141U: Factor w/ 3 levels "Week","Month",..: NA 1 NA NA NA NA NA NA 3 NA ...
 $ ALQ151 : Factor w/ 3 levels "Yes","No","Don't know": 1 1 2 2 2 2 2 2 2 2 ...
 $ ALQ160 : num  NA 0 NA NA 0 NA NA NA 0 NA ...
> str(nhanes("ALQ_I"))
'data.frame':	5735 obs. of  10 variables:
 $ SEQN   : num  83732 83733 83734 83735 83736 ...
 $ ALQ101 : Factor w/ 3 levels "Yes","No","Don't know": 1 1 1 2 2 2 1 1 NA 1 ...
 $ ALQ110 : Factor w/ 4 levels "Yes","No","Refused",..: NA NA NA 1 1 2 NA NA NA NA ...
 $ ALQ120Q: num  1 7 0 3 1 NA 3 1 NA 0 ...
 $ ALQ120U: Factor w/ 3 levels "Week","Month",..: 2 1 NA 3 3 NA 2 2 NA NA ...
 $ ALQ130 : num  1 6 NA 1 1 NA 8 1 NA NA ...
 $ ALQ141Q: num  0 7 NA 0 0 NA 20 0 NA NA ...
 $ ALQ141U: Factor w/ 3 levels "Week","Month",..: NA 1 NA NA NA NA 3 NA NA NA ...
 $ ALQ151 : Factor w/ 4 levels "Yes","No","Refused",..: 2 1 1 2 2 NA 1 2 NA 1 ...
 $ ALQ160 : num  NA 0 NA NA NA NA 2 NA NA NA ...
```

The general trend in recent years has been to move towards `stringsAsFactors = FALSE` by default. Should we also keep these as character strings instead of converting to factors?

**Comment by cjendres1** [comment]
I've thought about creating a row bind function that would standardize columns across cycles, but it seemed too difficult to generalize. My opinion is that this is in the realm of data cleaning and prep that is outside the scope of nhanesA. FWIW, I haven't received requests to convert categorical variables to character strings.

**Comment by deepayan** [comment]
Yes, I agree that combining across cycles is beyond the scope of nhanesA. Not least because the same variable may belong to different tables in different cycles. 

From a little bit of testing, R seems smart enough when combining factors that this should not be an issue. Still, we may eventually want to have a `stringsAsFactors` argument similar to `data.frame()` etc, but it's certainly not urgent.

**Comment by cjendres1** [comment]
Am closing this issue for now. If there's general interest in methodology to combine across cycles then perhaps we can give more comprehensive thought to that process.

**Comment by cjendres1** [comment]
Closing as "not planned" instead of "completed"
