### ISSUE TITLE
Inconsistency in codebook column names 

### ISSUE THREAD

**Issue by deepayan** [cjendres1/nhanes#64]
I was initially confused by this inconsistency in whether column names are 'fixed':

```
> nhanesCodebook('AUX_D', 'AUQ020D')$AUQ020D
# A tibble: 4 × 5
  `Code or Value` `Value Description`     Count Cumulative `Skip to Item`
  <chr>           <chr>                   <int>      <int> <lgl>         
1 1               Yes (checkbox checked)     11         11 NA            
2 2               No (checkbox unchecked)   342        353 NA            
3 9               Don't know                  1        354 NA            
4 .               Missing                  2680       3034 NA            
> nhanesTranslate('AUX_D', colnames = 'AUQ020D', details = TRUE)$AUQ020D
  Code.or.Value       Value.Description Count Cumulative Skip.to.Item
1             1  Yes (checkbox checked)    11         11           NA
2             2 No (checkbox unchecked)   342        353           NA
3             9              Don't know     1        354           NA
4             .                 Missing  2680       3034           NA
```

I eventually figured out that this is because `nhanesTranslate()` has

```r
  tabletrans <- html_elements(tabletree, 'table') |> html_table() |> as.data.frame()
```

while `nhanesCodebook()` does not have the `as.data.frame()` coercion.

```r
  tabletrans <- html_elements(tabletree, 'table') |> html_table()
```

I am conflicted about which is the right thing to do, but I guess we should at least be consistent? 

And a lot of the existing code assumes that the `as.data.frame()` coercion has been done, so probably that's the easiest choice for now.

**Comment by cjendres1** [comment]
`nhanesTranslate()` is intended to make changes to raw data, whereas `nhanesCodebook()` simply displays information (in list format). They each serve a distinct purpose, and the different output formats are intentional.  Are there use-cases where nhanesCodebook should return the translation table as a data frame?

**Comment by deepayan** [comment]
The issue is not tibble vs data.frame (tibbles are already data frames), but whether the column names have spaces in them. 

I have no strong feelings about this. I am considering some additional conversion for numeric variables, where values like "Don't know" or "Refused to answer" are coded with numeric values, but should be treated as missing for analysis. I was using `nhanesCodebook()` to get the conversion codes, and came across this perceived inconsistency. Now that I know this is intentional, I can easily work around it.
