### ISSUE TITLE
nhanes() is not working

### ISSUE THREAD

**Issue by HQData** [cjendres1/nhanes#7]
hi Chris, all other functions in the nhanesA package works well for me after loading the package, except the file importing function nhanes().  When I run demo <- nhanes('DEMO_I'), it tells me that the dataset DEMO_I is not available.  is something wrong with the way i am using the function? Please help. thanks,

**Comment by cjendres1** [comment]
Hi, very sorry for not responding sooner. Somehow I missed the notification.
I just tested this out on my system and the command worked for me. Please note that at times the NHANES server is down for maintenance and some data may not be accessed. Did you notice the problem for other tables or just for DEMO_I? In any case, please try the command again and let me know if you're still having the same problem.

All the best,
Chris
