### ISSUE TITLE
nhanesFromURL() missing columns on download

### ISSUE THREAD

**Issue by sam-pullman** [cjendres1/nhanes#79]
From the Doc for L06_2_B there should be a column LB2DAY, but upon inspecting the columns downloaded using nhanesFromURL() this column is missing.

colnames(nhanesFromURL("https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/L06_2_B.XPT"))
<img width="831" alt="image" src="https://github.com/cjendres1/nhanes/assets/101196589/a2f61a93-6454-47b1-8f52-0f355f4c0323">

**Comment by deepayan** [comment]
This looks like a CDC bug --- the data file really does not include the `LB2DAY` column. Apart from the `read.xport()` function not finding it, I also get no output from

```
$ strings L06_2_B.XPT | grep -i day
```

so this doesn't look like a bug in `read.xport()` either.

We should start putting together a list of things to report to CDC, but for now we will need to work around this.

**Comment by cjendres1** [comment]
There are numerous issues with missing variables or inconsistent naming (e.g. capitalization), particularly in the first few cycles. This example is from the 2nd continuous NHANES cycle. Definitely a CDC issue. I'll close as "Not Planned", but we may prepare a list of such issues to submit to CDC.
