### ISSUE TITLE
unable to browse or pull data/tables for modified cycle 2017-March2020 (prepandemic)

### ISSUE THREAD

**Issue by coding-rheum** [cjendres1/nhanes#82]
Thank you for this awesome package. Pardon me if it is obvious as I am "very beginner". I have been able to browse and pull data for all years/cycles except the most recent available as 3.2 yrs data 2017 to March 2020. Using 2017 as year points to 2017 - 2018 data which is okay, but not what i want. How can I point to the modified cycle 2017-2020?

**Comment by rgentlem** [comment]
Hi,  
  It is usually most helpful to show something you tried, and what happened. 
But this works for me:  xx = nhanes("P_DEMO")
so, are you using the CDC convention that these tables have a P_ in front of them?
This "P_DEMO NHANES" in Google gets you to the documentation page for that file.
The vignette in the package, either found on CRAN, or by using: vignette("Introducing_nhanesA")
has a section on how to get these files.

**Comment by coding-rheum** [comment]
Thank you so much. 
example code:
`demo2017-2020 <- nhanes('P_DEMO') ` did work to fetch the data. 

However, if I were to browse what tables are available in questionnaire data during that cycle with `nhanesTable("P_Q", XXXX)` -- I am unsure what argument would work for the year. 
`nhanesTable("P_Q", 2017)` produces an error like this:

Error in nhanesTable("P_Q", 2017): could not find function "nhanesTable"
Traceback:

**Comment by cjendres1** [comment]
For pre-pandemic tables, enter 'P' as the year. 
To get the pre-pandemic questionnaire tables use:
```nhanesTables('Q','P')```
