### ISSUE TITLE
Delete downloaded files?

### ISSUE THREAD

**Issue by deepayan** [cjendres1/nhanes#88]
I have faced some intermittent issues while doing bulk processing of NHANES tables, and I think they boil down to running out of temporary space. As far as I can tell, the XPT files are downloaded in a new `tempfile()` every time, which are never deleted. Does it seem reasonable to delete these temporary files once `read.xport()` has run without errors?

If there are no objections, I am happy to prepare a PR.

**Comment by cjendres1** [comment]
Absolutely, a PR to fix this is much appreciated. The temp files should be invisible to the user anyway. 
If you think there's a reason to keep temp files around a bit, then we could add an option (e.g. tempdelete = TRUE), but it's cleaner to just delete after the table is loaded.

**Comment by cjendres1** [comment]
Resolved in this PR: https://github.com/cjendres1/nhanes/pull/89
