### ISSUE TITLE
Extended Codebook Data

### ISSUE THREAD

**Issue by paynejason** [cjendres1/nhanes#9]
Hello,

This tool is very helpful, thank you for making it. I am currently working on a project with NHANES that also assesses the Codebook/variable data, so your nhanesTableVars functionality is life-saving. 

On that front, is there any way to extend that functionality to include the expected values and their keys? For example, variable `AUQ020D`  has label `Earache Last 24 Hours, Left? `, has a description `Have you had an earache in left ear in the last 24 hours?` and the set of expected values `Yes` `No` `Don't know` or `Missing`. The raw data does not exist in any form I have been able to find or download and it would be invaluable.

**Comment by cjendres1** [comment]
Hi Jason,
**nhanesTranslate** will retrieve the expected values for any variable
E.g., you can get all valid values for AUQ020D with 
**nhanesTranslate('AUX_D', "AUQ020D")**

nhanesTableVars with namesonly=TRUE will pass back the variable names. You can then loop through the variables and call nhanesTranslate for each desired variable.
Is that what you wanted?  

Thanks for using nhanesA!
Chris

**Comment by cjendres1** [comment]
Someone else also commented on the codebook label which is currently not returned by nhanesTranslate. Would help if you can write out a simple example of your desired output.

**Comment by paynejason** [comment]
Hi Chris,
Thank you for the response, the data was just what I was looking for!

In regards to the other person, we are actually working on the same project, so I'm not sure how much light I can shed on the situation. However, we are looking for the SAS Label and Target information as seen here:
<img width="655" alt="image" src="https://user-images.githubusercontent.com/100445045/186724246-48bb24f2-5699-4293-a1fc-b17f259d19f6.png">


Not sure if this helps, but thank you again!

**Comment by cjendres1** [comment]
That clears things up actually. If you want that full description returned including the text fields and the additional columns (Count, Cumulative, Skip) then the behavior is different enough from nhanesTranslate that I will create a new function: nhanesCodebook. Should have it ready in a couple days.

**Comment by cjendres1** [comment]
After further consideration ... this will be easier than I thought. Adding details = TRUE already gives you the last columns.
try
**nhanesTranslate('AUX_D', "AUQ020D", details=TRUE)**

Just need to add the text fields

**Comment by cjendres1** [comment]
[nhanesCodebook.txt](https://github.com/cjendres1/nhanes/files/9428493/nhanesCodebook.txt)
Please rename the attached file to nhanesCodebook.R  for some reason it doesn't allow attaching '.R' files
In your R session
1: source('nhanesCodebook.R')
2: nhanesCodebook('AUX_D', 'AUQ020D')

Let me know if the result of the last command is what you're looking for. It's a list since there's a mixture of data types.
Please test it out as much you can and let me know if there's any unexpected behavior.
Thanks!

**Comment by paynejason** [comment]
This is perfect, thank you so much for the help!
